CREATE TABLESPACE music_ts
    DATAFILE '/opt/oracle/oradata/FREE/music_ts01.dbf'
    SIZE 100M
    AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;
    
   
    
CREATE TABLE Musicians (
    musician_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    info        VARCHAR2(500),
    status      VARCHAR2(20) CHECK (status IN ('participating','disqualified')) NOT NULL
) TABLESPACE music_ts;

CREATE TABLE Albums (
    album_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    musician_id  NUMBER NOT NULL,
    title        VARCHAR2(150) NOT NULL,
    release_date DATE,
    link         VARCHAR2(200) NOT NULL,
    pic_link     VARCHAR2(100),
    CONSTRAINT fk_album_musician FOREIGN KEY (musician_id)
        REFERENCES Musicians(musician_id)
        ON DELETE CASCADE
) TABLESPACE music_ts;

CREATE TABLE Music (
    track_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id     NUMBER NOT NULL,
    title        VARCHAR2(150) NOT NULL,
    CONSTRAINT fk_music_album FOREIGN KEY (album_id)
        REFERENCES Albums(album_id)
        ON DELETE CASCADE
) TABLESPACE music_ts;

CREATE TABLE Users (
    user_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    gmail    VARCHAR2(100) NOT NULL UNIQUE,
    password_hash VARCHAR2(200) NOT NULL,
    role     VARCHAR2(20) DEFAULT 'guest_user'
        CONSTRAINT chk_role CHECK (role IN ('admin_user','manager_user','guest_user'))
) TABLESPACE music_ts;

CREATE TABLE Awards (
    award_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_name         VARCHAR2(150) NOT NULL,      
    award_description  VARCHAR2(500)
) TABLESPACE music_ts;

CREATE TABLE Nominants (
    award_id    NUMBER NOT NULL,
    album_id    NUMBER NOT NULL,
    CONSTRAINT pk_nominants PRIMARY KEY (award_id, album_id),
    CONSTRAINT fk_nominant_award FOREIGN KEY (award_id)
        REFERENCES Awards(award_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_nominant_album FOREIGN KEY (album_id)
        REFERENCES Albums(album_id)
        ON DELETE CASCADE
) TABLESPACE music_ts;

CREATE TABLE Winners (
    award_id     NUMBER NOT NULL,
    album_id     NUMBER NOT NULL,
    musician_id  NUMBER NOT NULL,
    CONSTRAINT pk_winners PRIMARY KEY (award_id, album_id),
    CONSTRAINT fk_winners_award FOREIGN KEY (award_id)
        REFERENCES Awards(award_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_winners_album FOREIGN KEY (album_id)
        REFERENCES Albums(album_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_winners_musician FOREIGN KEY (musician_id)
        REFERENCES Musicians(musician_id)
        ON DELETE CASCADE
) TABLESPACE music_ts;

CREATE TABLE Votes (
    vote_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_id     NUMBER NOT NULL,
    album_id     NUMBER NOT NULL,
    user_id      NUMBER NOT NULL,
    comment_text VARCHAR2(4000),
    CONSTRAINT uq_vote_user_award UNIQUE (user_id, award_id),
    CONSTRAINT fk_vote_award FOREIGN KEY (award_id)
        REFERENCES Awards(award_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_vote_album FOREIGN KEY (album_id)
        REFERENCES Albums(album_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_vote_user FOREIGN KEY (user_id)
        REFERENCES Users(user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_vote_nomination FOREIGN KEY (award_id, album_id)
        REFERENCES Nominants(award_id, album_id)
        ON DELETE CASCADE
) TABLESPACE music_ts;

CREATE TABLE AlbumRatings (
    award_id NUMBER NOT NULL,
    album_id NUMBER NOT NULL,
    votes_count NUMBER DEFAULT 0,
    PRIMARY KEY (award_id, album_id),
    CONSTRAINT fk_rating_award FOREIGN KEY (award_id)
        REFERENCES Awards(award_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_rating_album FOREIGN KEY (album_id)
        REFERENCES Albums(album_id)
        ON DELETE CASCADE
) TABLESPACE music_ts;


DROP TABLE AlbumRatings CASCADE CONSTRAINTS;
DROP TABLE Votes CASCADE CONSTRAINTS;
DROP TABLE Winners CASCADE CONSTRAINTS;
DROP TABLE Nominants CASCADE CONSTRAINTS;
DROP TABLE Awards CASCADE CONSTRAINTS;
DROP TABLE Music CASCADE CONSTRAINTS;
DROP TABLE Albums CASCADE CONSTRAINTS;
DROP TABLE Musicians CASCADE CONSTRAINTS;
DROP TABLE Users CASCADE CONSTRAINTS;

-----
DROP INDEX idx_users_role_username;

CREATE INDEX idx_users_role_username ON Users (role, username) TABLESPACE music_ts;


